### ISSUE TITLE
Produced dumps do not have symbols

### ISSUE THREAD

**Issue by krwq** [Microsoft/dumpling#27]
Currently dumpling does not produce actionable output because symbols are missing and thus debugging using the dump is not feasible. The dumpling also does not point to a build or hash commit which could be used to produce them.

Longer conversation about this: https://github.com/dotnet/corefx/issues/16988

From @schaabs 
> you can upload any associated symbols when you upload the dumps using the --incpaths flag

From @mellinoe
> We archive all of the product binaries in Jenkins, but don't upload them to Dumpling. Jenkins only keeps them around for a week or so, but if this is happening at least once per week anyways, then we should be able to get some matching binaries and dumps, right? We don't archive the test binaries / assemblies, but we could change that, and I think we could still gather useful info without them.

Example dumps which do not contain symbols:
https://dumpling.azurewebsites.net/90?FAILURE_HASH=SIGSEGV_libcrypto.so.1.0.0!BN_num_bits

**Comment by mellinoe** [comment]
@krwq This is more likely a problem with what we are uploading in buildtools, not a problem in Dumpling itself. I think what we need to do is just hook up the `--incpaths` parameter to the folder containing our runtime. That folder is already being persisted on Jenkins, so the improvement here would be to include it in the actual dumpling archive that you download (which is easier and better, I agree) rather than as a separate step.

**Comment by krwq** [comment]
@mellinoe is there some msbuild variable containing runtime path there? Why is the upload logic both in the python and shell script? How do you debug this locally? Any chance you could send a few lines PR with this change - you seem to have more context than me?

**Comment by sepidehMS** [comment]
@mellinoe From where do we get the runtime path? And does testing it on Windows (after updating BuildTools I mean) require doing any tricks other than using your local BuildTools and inserting a failing test which generates dumps?

**Comment by mellinoe** [comment]
> is there some msbuild variable containing runtime path there?

In corefx, `RuntimePath` contains the fully-built runtime. We may also want to include the test output path, since that includes test-specific binaries and symbols that could be useful for debugging.

> Why is the upload logic both in the python and shell script?

In buildtools, the shell script is just a "bootstrapper" which ends up calling the Dumpling python script. That's what is contained in this repo here, and does the most of the work.

> How do you debug this locally? 

Set `EnableDumpling` to true, and cause a test to seg-fault. When I tested it, I used this code snippet:

```C#
IntPtr ptr = new IntPtr(1);
Marshal.StructureToPtr(1, ptr, true);
```

> Any chance you could send a few lines PR with this change - you seem to have more context than me?

I think we just need to pass [`--incpaths`](https://github.com/Microsoft/dumpling/blob/master/src/web/Content/client/dumpling.py#L1041) to [our invocation of Dumpling.py](https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.CloudTestTasks/PackageFiles/DumplingHelper.py#L40). We'll need to plumb that through the targets files which hook into Dumpling.sh / DumplingHelper.py, and we will need to duplicate that effort for Windows/Unix right now.

That's assuming that `--incpaths` does what we want, but it sounds like it does.

> From where do we get the runtime path? And does testing it on Windows (after updating BuildTools I mean) require doing any tricks other than using your local BuildTools and inserting a failing test which generates dumps?

No, that should be all. Right now the scripts for Windows/Unix are separate, which means fixing it for Windows wouldn't fix it for Unix. Instead, we should just unify them and have both systems call `DumplingHelper.py` (that's what I wrote it for, I just didn't have time to unify them and test it).

**Comment by sepidehMS** [comment]
@mellinoe Thanks. What should CrashDumpFolder be set to on Windows?

**Comment by mellinoe** [comment]
Ah, that's a good point that I had forgotten. You have to configure Windows to persist crash dumps by setting some registry keys. [This article](https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181(v=vs.85).aspx) describes how to do it.

Essentially you just need to create a reg key named `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps\.exe` and set its value to something like `C:\localdumps\dotnet_exe\`.

You could also just try it on Linux, it may be easier there.

**Comment by danmosemsft** [comment]
Assume this is no longer an issue.
